manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: arch-tty
      url-base: https://github.com/Arch-TTY
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: prospector-zmk-module
      remote: arch-tty
      revision: feat/new-status-screens
    - name: zmk-locales
      remote: arch-tty
      revision: main
  self:
    path: config
